# Generated by Django 5.1 on 2024-08-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='xrpl_wallet_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
