# Generated by Django 5.1 on 2024-08-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_xrpl_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='xrpl_wallet_address',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
