swagger: '2.0'
info:
  title: 광운대학교 온라인 투표 시스템 API
  description: XRPL를 이용한 광운대학교 온라인 투표 시스템 API
  version: v1
host: 127.0.0.1:8000
schemes:
- http
basePath: /
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Basic:
    type: basic
security:
- Basic: []
paths:
  /posts/:
    get:
      operationId: posts_list
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Post'
      tags:
      - posts
    post:
      operationId: posts_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Post'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Post'
      tags:
      - posts
    parameters: []
  /posts/{id}/:
    get:
      operationId: posts_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Post'
      tags:
      - posts
    put:
      operationId: posts_update
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Post'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Post'
      tags:
      - posts
    patch:
      operationId: posts_partial_update
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Post'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Post'
      tags:
      - posts
    delete:
      operationId: posts_delete
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - posts
    parameters:
    - name: id
      in: path
      description: A unique integer value identifying this post.
      required: true
      type: integer
  /users/login/:
    post:
      operationId: users_login_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Login'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Login'
      tags:
      - users
    parameters: []
  /users/profile/{user}/:
    get:
      operationId: users_profile_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Profile'
      tags:
      - users
    put:
      operationId: users_profile_update
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Profile'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Profile'
      tags:
      - users
    patch:
      operationId: users_profile_partial_update
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Profile'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Profile'
      tags:
      - users
    parameters:
    - name: user
      in: path
      description: A unique value identifying this profile.
      required: true
      type: string
  /users/register/:
    post:
      operationId: users_register_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Register'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Register'
      tags:
      - users
    parameters: []
definitions:
  Profile:
    required:
    - nickname
    - department
    type: object
    properties:
      nickname:
        title: Nickname
        type: string
        maxLength: 128
        minLength: 1
      department:
        title: Department
        type: string
        maxLength: 128
        minLength: 1
      image:
        title: Image
        type: string
        readOnly: true
        format: uri
      xrpl_wallet_address:
        title: Xrpl wallet address
        type: string
        maxLength: 128
  Post:
    required:
    - title
    - content
    type: object
    properties:
      pk:
        title: ID
        type: integer
        readOnly: true
      profile:
        $ref: '#/definitions/Profile'
      title:
        title: Title
        type: string
        maxLength: 128
        minLength: 1
      content:
        title: Content
        type: string
        minLength: 1
      image:
        title: Image
        type: string
        readOnly: true
        format: uri
      likes:
        type: array
        items:
          type: integer
        uniqueItems: true
      published_date:
        title: Published date
        type: string
        format: date-time
      end_date:
        title: End date
        type: string
        format: date-time
        x-nullable: true
  Login:
    required:
    - username
    - password
    type: object
    properties:
      username:
        title: Username
        type: string
        minLength: 1
      password:
        title: Password
        type: string
        minLength: 1
  Register:
    required:
    - username
    - password
    - password2
    - email
    - xrpl_wallet_address
    type: object
    properties:
      username:
        title: Username
        description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
          only.
        type: string
        pattern: ^[\w.@+-]+$
        maxLength: 150
        minLength: 1
      password:
        title: Password
        type: string
        minLength: 1
      password2:
        title: Password2
        type: string
        minLength: 1
      email:
        title: Email
        type: string
        format: email
        minLength: 1
      xrpl_wallet_address:
        title: Xrpl wallet address
        type: string
        minLength: 1
